name: Add Issue to project
on:
  workflow_call:

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get project data
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/HChughtai/projects/3
          github-token: ${{ secrets.PHD_PROJECT_MANAGEMENT_PAT }}
